News:
  connection: doctrine
  comment: 'Новости'
  tableName: news
  actAs:
    Timestampable: ~
    Sortable: ~
  columns:
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      comment: 'Заголовок новости'
    announce:
      type: string(300)
      notnull: true
      comment: 'Анонс'
    description:
      type: clob
      notnull: true
      comment: 'Описание'
    image:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
      comment: 'Изображение'